
services:
  myapp-dev:
    image: nginx:latest
    container_name: myapp-dev
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    volumes:
      - ./dev:/usr/share/nginx/html
    networks:
      - myapp-net

  myapp-prod:
    image: nginx:latest
    container_name: myapp-prod
    ports:
      - "81:80"  # Map host port 81 to container port 80
    volumes:
      - ./production:/usr/share/nginx/html
    networks:
      - myapp-net

networks:
  myapp-net:
    driver: bridge
